module.exports = {
    '404': (req, cb) => cb(),
    'candidate-item': (req, cb) => cb(),
    'candidates': (req, cb) => cb(),
    'login': (req, cb) => cb(),
    'paper-item': (req, cb) => cb(),
    'papers': (req, cb) => cb(),
    'question-item': (req, cb) => cb(),
    'questions': (req, cb) => cb(),
    'results': (req, cb) => cb(),
    'schedule': (req, cb) => cb(),
    'schedules': (req, cb) => cb(),
    'setting': (req, cb) => cb(),
    'import': (req, cb) => cb(),
    'auto-schedules': (req, cb) => cb(),
    'auto-schedule-item': (req, cb) => cb(),
    'candidate-report': (req, cb) => cb(),
    'class-report': (req, cb) => cb()
};
