module.exports = {
    COLLS: {
        USER: 'users',
        SCHEDULE: 'dispatches',
        PAPER: 'paper',
        QUESTION: 'questions',
        ARTICLE: 'articles',
        CANDIDATE: 'students',
        RESULT: 'results',
        CANDIDATE_CATEGORY: 'candidate_categories',
        QUESTION_CATEGORY: 'question_categories',
        PAPER_CATEGORY: 'paper_categories',
        AUTO_SCHEDULE: 'auto_schedule',
        AUTO_SCHEDULE_QUEUE: 'auto_schedule_queue',
        PERMISSIONS: 'permissions',
        OPTIONS: 'options'
    },
    PERMISSIONS: {
        CREATE_CLASS: 'create_class',
        REMOVE_CLASS: 'remove_class',
        CREATE_SUBJECT: 'create_subject',
        REMOVE_SUBJECT: 'remove_subject',
        QUESTIONS: 'questions',
        REMOVE_QUESTION: 'remove_question',
        PAPERS: 'papers',
        REMOVE_PAPER: 'remove_paper',
        CANDIDATES: 'candidates',
        REMOVE_CANDIDATE: 'remove_candidate',
        RESULTS: 'results',
        SCHEDULES: 'schedules',
        REMOVE_SCHEDULE: 'remove_schedule',
        NEW_SCHEDULE: 'new_schedule',
        AUTO_SCHEDULE: 'auto_schedule',
        CANDIDATE_REPORT: 'candidate_report',
        CLASS_REPORT: 'class_report',
        IMPORT: 'import',
        USERS: 'users',
        PERMISSIONS: 'permissions',
        OPTIONS: 'options'
    }
};
